version: '3.8'

services:
  # FastAPI service
  fastapi:
    build:
      dockerfile: Dockerfile-fastapi
    ports:
      - "8000:8000"

  # Node.js service for server.js
  nodejs:
    build:
      dockerfile: Dockerfile-server
    ports:
      - "3001:3001"

  # Node.js service for the client app
  client:
    build:
      dockerfile: Dockerfile-client
    ports:
      - "3000:3000"

