# Use the official Python image as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the FastAPI files to the container's /app directory
COPY Fast-API /app

# Clone the YOLOv5 repository into the /app directory
RUN git clone https://github.com/ultralytics/yolov5 /app/yolov5

# Set the working directory to the /app directory
WORKDIR /app

# Install Python dependencies for FastAPI
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port that FastAPI will run on (inside the container)
EXPOSE 8000

# Command to start the FastAPI application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

